# Data collection

Source : (https://www.kaggle.com/datasets/joebeachcapital/30000-spotify-songs/data)

Playlists having an appropriate number of tracks are being selected for the project. At first, it was decided to collect the playlist with number of of tracks between 20 to 30 because I am doing the data splitting later in the evaluation and for each playlist, if the number of tracks is split into 80%-20%, that would give 16 to 24 tracks for input and 4 to 6 tracks for comparison which I think is an appropriate amount. However, there was only a few playlist (which contains between 20-30 tracks) and therefore, the total tracks were only 436 which is quite small. 
Therefore, I adjust the number of tracks in a playlist to be in a range 15-40 and that would be 12 to 32 tracks for input and 3 to 8 tracks for comparison and the total tracks is 1315 before data cleaning.

In [147]:
import pandas as pd
playlistData = pd.read_csv ("spotify_songs.csv", encoding="latin1")

# Select only a part of the playlists

# playlist_size table => playlist ids and number of tracks per playlist (count)
playlist_size = playlistData.groupby(playlistData['playlist_id']).size().reset_index(name='count')

# target_playlist_size table => playlist ids with size between 15 and 40 tracks
target_playlist_size = playlist_size [(playlist_size['count'] > 15) & (playlist_size['count'] < 40)]

# Cumulative count of tracks in target playlists
target_playlist_size['cumulative_count'] = target_playlist_size['count'].cumsum()

target_playlist = playlistData[playlistData['playlist_id'].isin(target_playlist_size['playlist_id'])]

target_playlist

C:\Users\PC\AppData\Local\Temp\ipykernel_20460\3290210888.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_playlist_size['cumulative_count'] = target_playlist_size['count'].cumsum()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
1497,4qEoqyPbLYnLOii6mKlIjI,"Determinate - From ""Lemonade Mouth""",Adam Hicks,64,6Vsml6sziVKBHxbMEp5wgQ,Lemonade Mouth,2011-01-01,Post teen pop,7jQHOrErpLMStcUUSavQWR,pop,...,1,-5.006,0,0.0488,0.003610,0.000000,0.0742,0.218,139.968,198107
1498,5lz0NiPw32Gq4kMIUJvuw2,"Take On the World - Theme Song From ""Girl Meet...",Rowan Blanchard,56,2gfzrQkA6WzsX13kOhf3wU,"Take On the World (Theme Song From ""Girl Meets...",2014-01-01,Post teen pop,7jQHOrErpLMStcUUSavQWR,pop,...,5,-6.475,1,0.0388,0.001030,0.000241,0.0466,0.703,115.967,192640
1499,1rM0CnyUiiw6A9CHJRXjZA,Chillin' Like a Villain,Sofia Carson,65,4Rk63Jz61wwbmQru0PdltI,Descendants 2 (Original TV Movie Soundtrack),2017-07-21,Post teen pop,7jQHOrErpLMStcUUSavQWR,pop,...,8,-6.664,1,0.0829,0.031800,0.000000,0.2320,0.827,113.886,193792
1500,744ZuzjXQmoJmOdk2I1ym9,"Keep It Undercover - Theme Song From ""K.C. Und...",Zendaya,52,4kQ2DrYRRIq0VTNKJOau2W,"Keep It Undercover (Theme Song From ""K.C. Unde...",2015-01-01,Post teen pop,7jQHOrErpLMStcUUSavQWR,pop,...,0,-4.444,1,0.0860,0.361000,0.000000,0.1960,0.803,109.974,156693
1501,6VcKAd94eVxNyudlWN91GH,"Time of Our Lives - Main Title Theme From ""I D...",Olivia Holt,41,1oT5sGw7p6B2EPC5fC8y8e,Time Of Our Lives (Main Title Theme) [Music Fr...,2014-01-01,Post teen pop,7jQHOrErpLMStcUUSavQWR,pop,...,2,-4.941,1,0.0879,0.000152,0.000594,0.1990,0.647,200.044,150507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30835,3sQfB3qhgsSTCdh55ai8zj,I Loved You Then,Luke & The Belleville Orchestra,35,07gCnkt7iO3U2FiXNPaccL,Speakeasy,2019-09-10,Tastemakers Ball - EDM - POP and FUN,67cpuBAXjwibm3LG333Oaq,edm,...,0,-6.211,1,0.2460,0.122000,0.000366,0.0847,0.891,119.990,183997
30836,7pr168TcvrcajZoKC0qxi7,Tokyo,Rewind,20,6j5tml7cagMte3dcTQWUVZ,Tokyo,2019-09-10,Tastemakers Ball - EDM - POP and FUN,67cpuBAXjwibm3LG333Oaq,edm,...,0,-7.164,1,0.0395,0.005160,0.432000,0.1410,0.336,128.005,214687
30837,05spZGjDdUaVc3QAv4ilY8,Bittersweet,The fire ants,0,1APhCSVU3drLIggbgPfCxU,Bittersweet,2018-12-28,Tastemakers Ball - EDM - POP and FUN,67cpuBAXjwibm3LG333Oaq,edm,...,0,-4.781,1,0.0673,0.013900,0.000000,0.1360,0.557,117.160,151714
30838,3IU7kPq7nceGAePo1hY2Ta,Ghost of You,Chris Kelly,0,3uTKfug3QM2EsvZxgPZm5O,Ghost of You,2017-06-05,Tastemakers Ball - EDM - POP and FUN,67cpuBAXjwibm3LG333Oaq,edm,...,0,-6.662,1,0.0321,0.004870,0.000457,0.2500,0.243,91.969,230672
30839,7j984GrN3brJOMNzXmffg7,wander,joeshort,0,69xGuJEhln7TnmNSIRq5V3,wander,2018-03-11,Tastemakers Ball - EDM - POP and FUN,67cpuBAXjwibm3LG333Oaq,edm,...,6,-12.662,0,0.0912,0.282000,0.862000,0.1020,0.829,82.969,104096

## Tracks file creation

Select fields for Tracks file. 
Audio features, track id, name and artist name will be included in the Tracks file.

In [148]:
tracks = target_playlist[['track_id', 'track_name', 'danceability', 'energy', 'valence', 'acousticness', 'tempo', 'instrumentalness','loudness']]
tracks.head()

,track_id,track_name,danceability,energy,valence,acousticness,tempo,instrumentalness,loudness
1497,4qEoqyPbLYnLOii6mKlIjI,"Determinate - From ""Lemonade Mouth""",0.562,0.768,0.218,0.003610,139.968,0.000000,-5.006
1498,5lz0NiPw32Gq4kMIUJvuw2,"Take On the World - Theme Song From ""Girl Meet...",0.638,0.713,0.703,0.001030,115.967,0.000241,-6.475
1499,1rM0CnyUiiw6A9CHJRXjZA,Chillin' Like a Villain,0.697,0.775,0.827,0.031800,113.886,0.000000,-6.664
1500,744ZuzjXQmoJmOdk2I1ym9,"Keep It Undercover - Theme Song From ""K.C. Und...",0.688,0.774,0.803,0.361000,109.974,0.000000,-4.444
1501,6VcKAd94eVxNyudlWN91GH,"Time of Our Lives - Main Title Theme From ""I D...",0.467,0.817,0.647,0.000152,200.044,0.000594,-4.941

## Artist Name and ID fetching from Spotify API

The original dataset uses '&' to store two or more artists for a track. Even if we split the two artists using delimiter '&', there can still be artists/bands with '&' in their name. So, I decided not to use the artist name (track_artist) provided by this dataset as it is not suitable to split the data using '&'.

Therefore, artist name and id are fetched through spotify track id. Both of them are stored as lists to handle multiple artists involving in a track.

In [149]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id="YOUR_CLIENT_ID",
    client_secret="YOUR_CLIENT_SECRET"
))

# fetching artist data function : give track id as input, to get artist id and name as an output
def get_artist_data(track_id):
    try: 
        track = sp.track(track_id)
        artist_id = [artist['id'] for artist in track['artists']]       #get artist ids list
        artist_name = [artist['name'] for artist in track['artists']]       #get artist names list
    except:
        artist_id = None
        artist_name = None
    return artist_id, artist_name

# store to the tracks dataframe
tracks[['artist_id', 'artist_name']] = tracks['track_id'].apply(lambda t: pd.Series(get_artist_data(t)))
tracks

C:\Users\PC\AppData\Local\Temp\ipykernel_20460\123951265.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks[['artist_id', 'artist_name']] = tracks['track_id'].apply(lambda t: pd.Series(get_artist_data(t)))
C:\Users\PC\AppData\Local\Temp\ipykernel_20460\123951265.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks[['artist_id', 'artist_name']] = tracks['track_id'].apply(lambda t: pd.Series(get_artist_data(t)))

,track_id,track_name,danceability,energy,valence,acousticness,tempo,instrumentalness,loudness,artist_id,artist_name
1497,4qEoqyPbLYnLOii6mKlIjI,"Determinate - From ""Lemonade Mouth""",0.562,0.768,0.218,0.003610,139.968,0.000000,-5.006,"[3dctbbXhrRgigX1icexnws, 4VhL8KLjVso4vLfOLVViT...","[Adam Hicks, Bridgit Mendler, Naomi Scott, Hay..."
1498,5lz0NiPw32Gq4kMIUJvuw2,"Take On the World - Theme Song From ""Girl Meet...",0.638,0.713,0.703,0.001030,115.967,0.000241,-6.475,"[45af7IeC0N5gQ9cyoIFyS6, 74KM79TiuVKeVCqs8QtB0B]","[Rowan Blanchard, Sabrina Carpenter]"
1499,1rM0CnyUiiw6A9CHJRXjZA,Chillin' Like a Villain,0.697,0.775,0.827,0.031800,113.886,0.000000,-6.664,"[7bp2lSdh12wcA8LyB1srfJ, 4uBD3fsHzb3IpOTGpicsb...","[Sofia Carson, Cameron Boyce, Booboo Stewart, ..."
1500,744ZuzjXQmoJmOdk2I1ym9,"Keep It Undercover - Theme Song From ""K.C. Und...",0.688,0.774,0.803,0.361000,109.974,0.000000,-4.444,[6sCbFbEjbYepqswM1vWjjs],[Zendaya]
1501,6VcKAd94eVxNyudlWN91GH,"Time of Our Lives - Main Title Theme From ""I D...",0.467,0.817,0.647,0.000152,200.044,0.000594,-4.941,[188VINPQh5dyNfLUkevKqf],[Olivia Holt]
...,...,...,...,...,...,...,...,...,...,...,...
30835,3sQfB3qhgsSTCdh55ai8zj,I Loved You Then,0.857,0.764,0.891,0.122000,119.990,0.000366,-6.211,[6SQIhvMZnAKCUJUDIWtiyH],[Luke & The Belleville Orchestra]
30836,7pr168TcvrcajZoKC0qxi7,Tokyo,0.700,0.593,0.336,0.005160,128.005,0.432000,-7.164,[7fmEsXLlUQCd6XacbLJaKc],[Rewind]
30837,05spZGjDdUaVc3QAv4ilY8,Bittersweet,0.886,0.801,0.557,0.013900,117.160,0.000000,-4.781,"[793YclcWIAfYR62mflICLo, 4FnaCBE2PNyhdX4HEcUvGw]","[The fire ants, Gorkem Han]"
30838,3IU7kPq7nceGAePo1hY2Ta,Ghost of You,0.510,0.769,0.243,0.004870,91.969,0.000457,-6.662,[0uYRrCyLgQWUaRGMSsHlzp],[Chris Kelly]
30839,7j984GrN3brJOMNzXmffg7,wander,0.740,0.494,0.829,0.282000,82.969,0.862000,-12.662,[5Fv1NLbpCj9pMsEps7KrO8],[joeshort]

## Data Preprocessing 
1. data cleaning : no nan values are found, no cleaning needed.
2. some changes to track name
2. getting to know the data

In [162]:
import re

# check if any nan values is there
print ("total nan values in df: ",tracks.isna().sum())

regexPatternsList = [r'\s*-\s*From.*\s*["\'].*["\']',            # - From ..." ... "   
                r'\s*-\s*Theme Song From\s*["\'].*["\']' ,       # - Theme Song From "..."
                r'\s*-\s*Main Title Theme From\s*["\'].*["\']', # - Main Title Theme From "..."
                r'\s*\(\s*Theme from .*\)\s*.*',                     # (Theme from ...) 
                r'\s*[\[\\(]\s*feat\..*[\]\\)]',                                  # (feat. ...) or [feat. ...]
                r'\s*-\s*feat\..*',                                      # feat.
                r'\s*\(\s*with.*\)',                                     # (with ...)
                r'\s*\(\s*.*Remix.*\)',                                     # (... Remix ...)
                r'\s*-.*Remix.*',                                         # - ... Remix ...
                r'\s*-\s*[Remastered|Remasterizado].*',                 # - Remastered ... or - Remasterizado...
                r'\s*\(\s*Remastered\s*.*\)',            # ( Remastered ....) 
                r'\s*-\s*\d{4}\s*Remaster(ed)?\s*',  # - 2008 Remaster 
                r'\s*\(\s*Original Mix\s*\)',          # (Original Mix)
                r'\s*-\s*Original Mix.*'              # - Original Mix
]
regexPatterns = '|' . join(regexPatternsList)

tracks['fixed_track_name'] = tracks['track_name'].str.replace(regexPatterns, '', flags=re.IGNORECASE, regex=True)

tracks.describe()

total nan values in df:  track_id             0
track_name           0
danceability         0
energy               0
valence              0
acousticness         0
tempo                0
instrumentalness     0
loudness             0
artist_id            0
artist_name          0
fixed_track_name     0
normalized_vector    0
weighted_vector      0
dtype: int64

C:\Users\PC\AppData\Local\Temp\ipykernel_20460\2307080907.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks['fixed_track_name'] = tracks['track_name'].str.replace(regexPatterns, '', flags=re.IGNORECASE, regex=True)

,danceability,energy,valence,acousticness,tempo,instrumentalness,loudness
count,1315.000000,1315.000000,1315.000000,1315.000000,1315.000000,1315.000000,1315.000000
mean,0.648997,0.706756,0.530373,0.175125,118.434112,0.079150,-7.027078
std,0.164345,0.187036,0.241034,0.225759,28.478783,0.213034,3.849171
min,0.077100,0.000175,0.000010,0.000012,52.654000,0.000000,-46.448000
25%,0.541000,0.594500,0.349000,0.013450,95.985000,0.000000,-8.600500
50%,0.678000,0.741000,0.544000,0.071100,115.614000,0.000014,-6.215000
75%,0.779500,0.852000,0.716500,0.246500,131.824000,0.005950,-4.532000
max,0.979000,1.000000,0.977000,0.994000,205.733000,0.994000,1.275000

## Features to Vector
1. Normalization
2. Weighting

## 1. Normalization
min-max normalization is used. Sklearn has MinMaxScalar() and it is used to normalize the features.

In [157]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler
scaler = MinMaxScaler()

# features to be normalized
features_vector = ['danceability', 'energy', 'valence', 'acousticness', 'tempo', 'instrumentalness', 'loudness']
print("Original  :", tracks.iloc[0][features_vector].tolist())
normalized = scaler.fit_transform(tracks[features_vector])      # 2D array
tracks["normalized_vector"] = normalized.tolist()       # transform to list to add to dataframe
tracks.head()
print("Normalized  :", tracks.iloc[0]['normalized_vector'], type(tracks.iloc[0]['normalized_vector']))

Original  : [np.float64(0.562), np.float64(0.768), np.float64(0.218), np.float64(0.00361), np.float64(139.968), np.float64(0.0), np.float64(-5.006)]
Normalized  : [0.5376427541856083, 0.7679593928937565, 0.22312408520046265, 0.003619762009199307, 0.5703852259290954, 0.0, 0.8683863126794208] <class 'list'>

C:\Users\PC\AppData\Local\Temp\ipykernel_20460\1272118359.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks["normalized_vector"] = normalized.tolist()       # transform to list to add to dataframe

## 2. Weighting

Energy, valence and acousticness can better discriminate the songs. (1.4 and 1.3 weightings are given to those.)

Instrumentalness and loudness are better than danceability and tempo at discriminating songs. (1.2 and 1.1 weightings are given respectively.)

In [158]:
weight_list = np.array([
        1.1,  # danceability
        1.4,  # energy
        1.3,  # valence     
        1.3,  # acousticness
        1.1,  # tempo
        1.2,  # instrumentalness
        1.2   # loudness
])

# Weighting : multiply each normalized vector by its corresponding weight (numpyarray * numpyarray) -> convert back to python list
tracks["weighted_vector"] = tracks["normalized_vector"].apply(lambda norm_v: (np.array(norm_v) * weight_list).tolist())

tracks.head()

print("Original  :", tracks.iloc[0][features_vector].tolist())
print("Normalized:", tracks.iloc[0]["normalized_vector"])
print("Weighted  :", tracks.iloc[0]["weighted_vector"])

Original  : [np.float64(0.562), np.float64(0.768), np.float64(0.218), np.float64(0.00361), np.float64(139.968), np.float64(0.0), np.float64(-5.006)]
Normalized: [0.5376427541856083, 0.7679593928937565, 0.22312408520046265, 0.003619762009199307, 0.5703852259290954, 0.0, 0.8683863126794208]
Weighted  : [0.5914070296041691, 1.075143150051259, 0.29006131076060143, 0.004705690611959099, 0.6274237485220049, 0.0, 1.042063575215305]

C:\Users\PC\AppData\Local\Temp\ipykernel_20460\586751135.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracks["weighted_vector"] = tracks["normalized_vector"].apply(lambda norm_v: (np.array(norm_v) * weight_list).tolist())

## Removing duplicate tracks

Only 5 tracks are duplicate, and 1310 tracks are left to be stored in the database as a music library for my project.

These tracks are ready to be stored in the system database.

In [159]:
# remove duplicate tracks based on track_id
final_tracks = tracks.drop_duplicates(subset="track_id", keep="first")
final_tracks

,track_id,track_name,danceability,energy,valence,acousticness,tempo,instrumentalness,loudness,artist_id,artist_name,fixed_track_name,normalized_vector,weighted_vector
1497,4qEoqyPbLYnLOii6mKlIjI,"Determinate - From ""Lemonade Mouth""",0.562,0.768,0.218,0.003610,139.968,0.000000,-5.006,"[3dctbbXhrRgigX1icexnws, 4VhL8KLjVso4vLfOLVViT...","[Adam Hicks, Bridgit Mendler, Naomi Scott, Hay...",Determinate,"[0.5376427541856083, 0.7679593928937565, 0.223...","[0.5914070296041691, 1.075143150051259, 0.2900..."
1498,5lz0NiPw32Gq4kMIUJvuw2,"Take On the World - Theme Song From ""Girl Meet...",0.638,0.713,0.703,0.001030,115.967,0.000241,-6.475,"[45af7IeC0N5gQ9cyoIFyS6, 74KM79TiuVKeVCqs8QtB0B]","[Rowan Blanchard, Sabrina Carpenter]",Take On the World,"[0.621909302583435, 0.7129497662090866, 0.7195...","[0.6841002328417786, 0.9981296726927211, 0.935..."
1499,1rM0CnyUiiw6A9CHJRXjZA,Chillin' Like a Villain,0.697,0.775,0.827,0.031800,113.886,0.000000,-6.664,"[7bp2lSdh12wcA8LyB1srfJ, 4uBD3fsHzb3IpOTGpicsb...","[Sofia Carson, Cameron Boyce, Booboo Stewart, ...",Chillin' Like a Villain,"[0.6873267546291163, 0.774960618108169, 0.8464...","[0.756059430092028, 1.0849448653514364, 1.1004..."
1500,744ZuzjXQmoJmOdk2I1ym9,"Keep It Undercover - Theme Song From ""K.C. Und...",0.688,0.774,0.803,0.361000,109.974,0.000000,-4.444,[6sCbFbEjbYepqswM1vWjjs],[Zendaya],Keep It Undercover,"[0.6773478212662158, 0.7739604430775386, 0.821...","[0.7450826033928375, 1.083544620308554, 1.0684..."
1501,6VcKAd94eVxNyudlWN91GH,"Time of Our Lives - Main Title Theme From ""I D...",0.467,0.817,0.647,0.000152,200.044,0.000594,-4.941,[188VINPQh5dyNfLUkevKqf],[Olivia Holt],Time of Our Lives,"[0.4323095686883247, 0.816967969394644, 0.6622...","[0.4755405255571572, 1.1437551571525015, 0.860..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30835,3sQfB3qhgsSTCdh55ai8zj,I Loved You Then,0.857,0.764,0.891,0.122000,119.990,0.000366,-6.211,[6SQIhvMZnAKCUJUDIWtiyH],[Luke & The Belleville Orchestra],I Loved You Then,"[0.864730014414015, 0.763958692771235, 0.91197...","[0.9512030158554166, 1.069542169879729, 1.1855..."
30836,7pr168TcvrcajZoKC0qxi7,Tokyo,0.700,0.593,0.336,0.005160,128.005,0.432000,-7.164,[7fmEsXLlUQCd6XacbLJaKc],[Rewind],Tokyo,"[0.6906530657500832, 0.5929287625334433, 0.343...","[0.7597183723250917, 0.8301002675468205, 0.447..."
30837,05spZGjDdUaVc3QAv4ilY8,Bittersweet,0.886,0.801,0.557,0.013900,117.160,0.000000,-4.781,"[793YclcWIAfYR62mflICLo, 4FnaCBE2PNyhdX4HEcUvGw]","[The fire ants, Gorkem Han]",Bittersweet,"[0.8968843552500279, 0.8009651689045584, 0.570...","[0.9865727907750307, 1.1213512364663816, 0.741..."
30838,3IU7kPq7nceGAePo1hY2Ta,Ghost of You,0.510,0.769,0.243,0.004870,91.969,0.000457,-6.662,[0uYRrCyLgQWUaRGMSsHlzp],[Chris Kelly],Ghost of You,"[0.47998669475551625, 0.7689595679243868, 0.24...","[0.5279853642310679, 1.0765433950941414, 0.323..."
30839,7j984GrN3brJOMNzXmffg7,wander,0.740,0.494,0.829,0.282000,82.969,0.862000,-12.662,[5Fv1NLbpCj9pMsEps7KrO8],[joeshort],wander,"[0.7350038806963078, 0.49391143450103764, 0.84...","[0.8085042687659387, 0.6914760083014526, 1.103..."

# Playlists file creation

Playlist id and track id are essential to be used as input, and I will also add track name and playlist name to know their names.

No need to remove duplications for this dataframe. This dataframe is for evaluation and is now ready to be used for evaluation.

In [160]:
final_playlists = target_playlist[['track_id', 'track_name', 'playlist_id', 'playlist_name']]
final_playlists

,track_id,track_name,playlist_id,playlist_name
1497,4qEoqyPbLYnLOii6mKlIjI,"Determinate - From ""Lemonade Mouth""",7jQHOrErpLMStcUUSavQWR,Post teen pop
1498,5lz0NiPw32Gq4kMIUJvuw2,"Take On the World - Theme Song From ""Girl Meet...",7jQHOrErpLMStcUUSavQWR,Post teen pop
1499,1rM0CnyUiiw6A9CHJRXjZA,Chillin' Like a Villain,7jQHOrErpLMStcUUSavQWR,Post teen pop
1500,744ZuzjXQmoJmOdk2I1ym9,"Keep It Undercover - Theme Song From ""K.C. Und...",7jQHOrErpLMStcUUSavQWR,Post teen pop
1501,6VcKAd94eVxNyudlWN91GH,"Time of Our Lives - Main Title Theme From ""I D...",7jQHOrErpLMStcUUSavQWR,Post teen pop
...,...,...,...,...
30835,3sQfB3qhgsSTCdh55ai8zj,I Loved You Then,67cpuBAXjwibm3LG333Oaq,Tastemakers Ball - EDM - POP and FUN
30836,7pr168TcvrcajZoKC0qxi7,Tokyo,67cpuBAXjwibm3LG333Oaq,Tastemakers Ball - EDM - POP and FUN
30837,05spZGjDdUaVc3QAv4ilY8,Bittersweet,67cpuBAXjwibm3LG333Oaq,Tastemakers Ball - EDM - POP and FUN
30838,3IU7kPq7nceGAePo1hY2Ta,Ghost of You,67cpuBAXjwibm3LG333Oaq,Tastemakers Ball - EDM - POP and FUN
30839,7j984GrN3brJOMNzXmffg7,wander,67cpuBAXjwibm3LG333Oaq,Tastemakers Ball - EDM - POP and FUN

## Print final_tracks and final_playlists to CSV

In [161]:
final_tracks.to_csv("tracks.csv", index=False)
final_playlists.to_csv("playlists.csv", index=False)