Importing Libraries

In [31]:
import requests
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

Loading playlist data

In [19]:
playlists = pd.read_csv("playlists.csv")
playlists.head()

,track_id,track_name,playlist_id,playlist_name
0,4qEoqyPbLYnLOii6mKlIjI,"Determinate - From ""Lemonade Mouth""",7jQHOrErpLMStcUUSavQWR,Post teen pop
1,5lz0NiPw32Gq4kMIUJvuw2,"Take On the World - Theme Song From ""Girl Meet...",7jQHOrErpLMStcUUSavQWR,Post teen pop
2,1rM0CnyUiiw6A9CHJRXjZA,Chillin' Like a Villain,7jQHOrErpLMStcUUSavQWR,Post teen pop
3,744ZuzjXQmoJmOdk2I1ym9,"Keep It Undercover - Theme Song From ""K.C. Und...",7jQHOrErpLMStcUUSavQWR,Post teen pop
4,6VcKAd94eVxNyudlWN91GH,"Time of Our Lives - Main Title Theme From ""I D...",7jQHOrErpLMStcUUSavQWR,Post teen pop

Data Preparation for evaluation : Grouping the data by Playlist ID and Name

In [ ]:
# Grouping by the playlist id and name
# converting track ids into a list for each playlist
playlist_data = playlists.groupby(['playlist_id', 'playlist_name'])['track_id'].apply(list).reset_index()
playlist_data.head()

,playlist_id,playlist_name,track_id
0,0BwUQpqHSlC2YfKwOp2dQV,Gangsta Rap ð Rap Party,"[5jAeM4WKpqDX9wDJGa7IFq, 3QbglwFgPJDHq7TbmUb3I..."
1,0DdGqNa18DwYyfIR05OrW1,Viral Southern Hip Hop,"[53v6w87pm4hVFwC7GlT2JI, 0M9mH33xccGM4ITZIGwX2..."
2,0QN4FeJQ1mpCygRg9r2JIK,Permanent wave ð,"[6zfczP87XO2SxWlQtnjFNa, 6iRrt1UtrgsxsOZUjp6Vg..."
3,0TT57Pe3RZNGCy98G1UQpM,TROPICALð´,"[3zbSYBDUbDEbqUIlCmOw09, 1siV5UzcXuFK5tMUVQ5Ki..."
4,0VS9w0NY4KXfLORkhY81s8,Permanent Wave Cafe,"[42T2QQv3xgBlpQxaSP7lnK, 3jxrPXWriZPIXKGbuniXh..."

The number of playlists to be used in evaluation.

In [35]:
print ("Number of playlists to be used in evaluation : ",len(playlist_data))

Number of playlists to be used in evaluation :  51

Getting the tracks of each playlist ready for the evaluation

In [40]:
input_tracks_list = [] # a variable to store the lists of input_tracks from each playlist
expected_tracks_list = [] # a variable to store the lists of expected_tracks (the ground truth) from each playlist

for _, row in playlist_data.iterrows():
    # get tracks of each playlist
    tracks = row['track_id'].copy()

    # shuffle the tracks of each playlist
    np.random.shuffle(tracks)

    # split the tracks of each playlist (80%, 20%)
    # 80% for input
    # 20% for expected tracks ground truth
    input_tracks, expected_tracks = train_test_split(tracks, test_size=0.2, random_state=42)
    
    # storing the lists of tracks from each playlist in the list
    input_tracks_list.append(input_tracks)
    expected_tracks_list.append(expected_tracks)

In [45]:
print ("Number of the lists of input_tracks : ", len(input_tracks_list))
print ("Number of the lists of expected_tracks : ", len(expected_tracks_list))

Number of the lists of input_tracks :  51
Number of the lists of expected_tracks :  51

In [ ]:
# Euclidean API URL
modelEuclideanURL = "http://127.0.0.1:8080/api/recommend/"

# for each playlist, inputs (list of tracks) are given to recommender logic
for track_lists in input_tracks_list: 
    # data preparation for input 
    json_payload = {
        "track_ids" : track_lists,
        # no preference is also okay (here it is default weight of 1.0)
        "preferences": {
            "energy_weight": 1.0,
            "tempo_weight": 1.0
        }
    }
    
    # post with input to url 
    response = requests.post(modelEuclideanURL, json= json_payload)
    data = response.json()
    print(data["track_id"])

In [ ]:


json_payload = {
  "track_ids": ["4qEoqyPbLYnLOii6mKlIjI", "5lz0NiPw32Gq4kMIUJvuw2","5q21u5TzhSaJPslac3xce8", "5Klo65Y9uouLjNVDV3pqh7"],
  "preferences": {
    "energy_weight": 1.2,
    "tempo_weight": 1.0
  }
}


print (response.text)
data = response.json()
print(data["track_id"])

{"track_id":"05RgAMGypEvqhNs5hPCbMS"}
05RgAMGypEvqhNs5hPCbMS